/* *************************************************************
TTEMDAT423.HPP - object to read and write the structure of the
	       output data from files generated by the Terrestrial 
	       Ecosystem Model (TEM)
************************************************************** */
using namespace std;
#if !defined(TTEMDAT423_H)
#define TTEMDAT423_H

class Temdata {
  
  public:
	
     Temdata(void);

/* **************************************************************
		 Public Functions
************************************************************** */

     int get(ifstream& ifile);
     int getdel(FILE* ifile);
     void getyrsum(double months[CYCLE]);
     void out(ofstream& ofile, float col, float row, char varname[9], int tveg, int subtveg, double psiplusc, int qlcon, int carea, long year, double mon[CYCLE], char contnent[9]);
     void outdel(ofstream& ofile, float col, float row, char varname[9], int tveg, int subtveg, double psiplusc, int qlcon, int carea, long year, double mon[CYCLE], char contnent[9]);
     void pctout(ofstream& ofile, float col, float row, char varname[9], int tveg, int subtveg, double psiplusc, int qlcon, int carea, long year, double mon[CYCLE], char contnent[9]);
     void poutdel(ofstream& ofile, float col, float row, char varname[9], int tveg, int subtveg, double psiplusc, int qlcon, int carea, long year, double mon[CYCLE], char contnent[9]);
		 void dayoutdel(ofstream& ofile, float col, float row, char varname[9], int tveg, int subtveg, double psiplusc, int qlcon, int carea, long year, double dat[CYCLE][31], char contnent[9], int days[CYCLE]);
/* **************************************************************
		 Public Variables
************************************************************** */

/* NOTE:  substitute "daily" for "monthly" if CYCLE = 365 rather than
	  CYCLE = 12 */


     float col;               // column or longitude of grid cell (degrees)
     float row;               // row or latitude of grid cell (degrees)
     char varname[9];         // name of TEM output variable
     int tveg;                // vegetation type of grid cell (categorical data)
     int subtveg;             //
     double psiplusc;         // percent silt plus percent clay of the grid cell
     int qlcon;               // quality control flag
     int carea;               // area covered by grid cell (square kilometers)
     long year;               // date (year) of data (transient version of TEM)
			     // number of years till equilibrium (equilibrium version of TEM)
     double total;            // annual sum of monthly data for the grid cell
     double max;              // maximum monthly value for the grid cell
     double ave;              // mean annual value for the grid cell
     double min;              // minimum monthly value for the grid cell
     double mon[CYCLE];       // monthly values of the TEM output variable for the grid cell
     double daydat[CYCLE][31];  // daily values of the TEM output for N flux
     char contnent[9];        // name of continent containing grid cell
    

  private:

/* **************************************************************
		      Private Variables
************************************************************** */

     int temend;
     long curpos;
     long lagpos;

};

#endif

